### ISSUE TITLE
CRA project import Error

### ISSUE THREAD

**Issue by codecomeon** [gronxb/webview-bridge#11]
Init a create-react-app, and import @webview-bridge/web，will get this error!

Module not found: Default condition should be last one
> 1 | import { linkNativeMethod, registerWebMethod } from '@webview-bridge/web';

**Comment by codecomeon** [comment]
But in a vue3 based vite project, it workd fine!

**Comment by gronxb** [comment]
Thanks for the report! I'll check it out today 😊 .

**Comment by doyoonkim12345** [comment]
I have same error too.

i am really looking forward to this project.

environment : react 18 with vite

if it fixed , i'm gonna use this package to my project very quickly

**Comment by gronxb** [comment]
> I have same error too.
> 
> i am really looking forward to this project.
> 
> environment : react 18 with vite
> 
> if it fixed , i'm gonna use this package to my project very quickly


I have it working fine in vite and react 18.  But I don't have time to check it in detail yet, I'll do it later today.

https://github.com/gronxb/webview-bridge-example/blob/main/apps/web/package.json#L13-L27

**Comment by gronxb** [comment]
Fixed in [v1.1.1](https://www.npmjs.com/package/@webview-bridge/web), thank you.
