### ISSUE TITLE
what is the best practice to call hooks in react native from hooks

### ISSUE THREAD

**Issue by doyoonkim12345** [gronxb/webview-bridge#13]
hi !

iam a fan of this project.

now i am using this project into my company's main project.

i think this project has a potential power.

I Love it.

I want to call a hook from web to rn web by this package.

i want to know what is the best practice

Can you explain Some?

i hope many people love this project

**Comment by gronxb** [comment]
Hi. Thank you so much for the great review. It encourages me to maintain this library. 🥹🥹🥰

Are you looking to use this as a hook for implementing a web method in React Native? If so, I'd appreciate more details about your specific scenario.
Or, are you considering using it as a hook in a web environment (React), while utilizing React Native methods?

And the common thread in both is that i want to understand why you need a hook.
I think the use cases that require hooks are related to `state integration` or `method export`.


**For state integration**: We would use a getter to obtain the raw value. However, this approach isn't very reactive. Periodically calling the method to retrieve the value is necessary, and utilizing `@tanstack/query` for management seems to be a suitable solution.

**For method exporting**: It's possible to export your `WebMethod` or `nativeMethod` without using a hook, allowing usage in any context independent of the React lifecycle.

When I designed it, I designed it not to depend on the framework, so I would say just use it.
But I think there are some scenarios that I don't know.


If there's a better way, I would consider integrating something.

So I need a more specific scenario🙏. Thanks

**Comment by doyoonkim12345** [comment]
Thank you for your fast replying,

My specific scenarios are here,

1. click a button in web, to open the modal in the react native app.
2. get the text which is dynamically changing in the web input tag and show it in Text tag in react-native.

**Comment by gronxb** [comment]
Thanks for sharing your scenarios.
I'm thinking of a good solution for `scenario #1` and will prepare it as soon as possible.
For example, `useAppBridgeSubscriber(appBridge, (returnValue) => void)` ?

I'm still thinking about this one.

As a solution for `scenario #2`, I am considering a reactive approach that is integrated into certain frameworks, such as `@webview-bridge/react` and `@webview-bridge/vue`.

I'll prepare this as well.

**Comment by gronxb** [comment]
hey @doyoonkim12345 , I've been busy and it takes time to prepare new features 😂 .

But I think the scenario you described can be solved with global state.
Below is an example using jotai.

## React Native Part
```tsx
import { atom, useAtomValue, getDefaultStore } from "jotai";

const textAtom = atom("");
const defaultStore = getDefaultStore();

export const appBridge = bridge({
  async setText(value: string) {
    defaultStore.set(textAtom, value);
  },
});


function ReactNativeComponent() {
  const text = useAtomValue(textAtom);

  return <Text>{text}</Text>;
}
```


## Web Part
```tsx
function WebComponent() {
  const [text, setText] = useState("");

  return (
    <input
      value={text}
      onChange={(e) => {
        setText(e.target.value);
        nativeMethod.setAtom(e.target.value);
      }}
    />
  );
}
```

**Comment by doyoonkim12345** [comment]
oh I see. you are in hard work. 

it doesnt seem that the way React wants. because get / set state outside of the hook / components. 

but it can be used.

thank you for telling me the good way.

i am going to use this way first, after your development is completed, i will migrate from this way. 

thanks.

**Comment by gronxb** [comment]
In v1.3.1 introduced the `shared state` feature !🥰

I can confirm that both of the scenarios you suggested will work.

Please check the documentation and examples.

Docs:
https://gronxb.github.io/webview-bridge/shared-state/react-native.html

Example:
https://github.com/gronxb/webview-bridge/tree/main/example/shared-state-integration-react

**Comment by doyoonkim12345** [comment]
wow amazing that's what i want.

after i looked this new feature, i updated the both of packages. if occurs a error.

if changed the method linkNativeMethod => linkBridge , then the webview only show the white screen. 

now iam Searching for reason why.

thank you for your work.

i am going to check out specific reason it doesn't work and then re comment.

thank you.

**Comment by gronxb** [comment]
If you create a simple reproduction repository, I can help expedite the process.

**Comment by doyoonkim12345** [comment]
hi i am sorry to make you waiting my reply.

i was trying to create reproduction. but i cannot make the same problem on reproduction.

i removed every nodemodules in monorepo and reinstall them.
and the it works well.

thank you

**Comment by gronxb** [comment]
Is this completely resolved?
