### ISSUE TITLE
Module not found:  Unable to use in Next.JS

### ISSUE THREAD

**Issue by rizshivalli** [gronxb/webview-bridge#32]
Init Next.JS project and import @webview-bridge/web，will get this error!

Module not found: Default condition should be last one

`> 57 | import { linkBridge } from "@webview-bridge/web";
  58 | import { useBridge } from "@webview-bridge/react";
  59 |
  60 | const bridge = linkBridge({

https://nextjs.org/docs/messages/module-not-found`

<img width="988" alt="Screenshot 2024-03-22 at 8 42 04 PM" src="https://github.com/gronxb/webview-bridge/assets/35989813/c4260d4b-aa56-4e55-a36f-c94d63f7ec0b">

**Comment by gronxb** [comment]
Thank you for your report. I will resolve it as soon as possible!

**Comment by akshat-rawat** [comment]
I am also facing the same issue.

**Comment by gronxb** [comment]
It has been resolved in v1.4.0!

Please check the guide in the document here:
https://gronxb.github.io/webview-bridge/ssr/next-js-app-router.html

For example code, visit:
https://github.com/gronxb/webview-bridge-example/blob/main/apps/next/src/components/BridgeHome.tsx

**Comment by gronxb** [comment]
My library relies on information from React Native to obtain state, but during the hydration process, it is difficult to obtain information about the app on the server side, so I must adopt a method to avoid hydration.

Thank you.
