### ISSUE TITLE
Bridge object is always empty.

### ISSUE THREAD

**Issue by rranjan14** [gronxb/webview-bridge#36]
Printing bridge object always comes out as empty object and cannot access methods by passing the bridge around. Followed the setup given in the docs. Not sure what's going wrong. However, I am able to access the methods by using the `useBridge` hook.

**Comment by gronxb** [comment]
Hi 👋 

If printing results in an empty object, but using useBridge allows it to function correctly, it can be considered to be working properly. The reason an empty object appears is that the value of the bridge is a proxy, which may not display correctly when printed. However, accessing its properties should work as expected.

javascript
Copy code
bridge.yourMethod(); // okay
const { yourMethod } = useBridge(appBridge); // okay
If both of these are working well, then it is likely functioning as intended.

**Comment by gronxb** [comment]
If only the `useBridge` hook is working, you might be in an SSR environment like `Next.js` or `Remix`. In this case, direct access to the `bridge` object might fail.

If you are in an SSR environment, it should work fine.

Please give me more information about your environment .. !

**Comment by gronxb** [comment]
The issue is being closed because it is stale.
