### ISSUE TITLE
Upgrading from 1.4.1 to latest version gives errors in Next.JS

### ISSUE THREAD

**Issue by steelzeh** [gronxb/webview-bridge#54]
Thank you for all the great work you are doing!

I have recently come across an issue in Next.js
In version 1.4.1 everything seems to be working great, but when upgrading to the latest version I'm getting these errors

`Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`

`The result of getServerSnapshot should be cached to avoid an infinite loop`

The code in particular occurs when using `useBridgeStore` inside a provider, here I have the LocationProvider where I use the `useBridgeStore` and the issues occur. These do not happen in 1.4.1

Here is a small sandbox where the issue is reproduced
https://codesandbox.io/p/sandbox/bridge-error-6mqtgj

**Comment by gronxb** [comment]
Thank you for providing the sandbox. I will check it out soon.

**Comment by nick0504k** [comment]
It happened to me as well but it was other cause. Do you happen to use yarn pnp ? If so, try nodeLinker: node-modules in .yarnrc.yml and remove pnp.js and .lock files and yarn install it may works

**Comment by steelzeh** [comment]
> I had a similar issue, but for a different reason. If you’re using Yarn Plug’n’Play (PnP), you might want to try setting nodeLinker: node-modules in your .yarnrc.yml file. Then, remove pnp.js and your .lock files, and run yarn install again. This might solve the problem.

Unfortunately this also happens when simply using npm

**Comment by gronxb** [comment]
Hey, @steelzeh 

I have confirmed that the issue occurs correctly work in the React Native WebView environment, but it causes errors in normal access.

Therefore, this issue has been resolved in version 1.5.3.

Here is the CodeSandbox for version 1.5.3 on the same codebase:
https://codesandbox.io/p/devbox/bridge-error-forked-sfkq6w

Let me know if you need any more changes!

**Comment by steelzeh** [comment]
> Hey, @steelzeh
> 
> I have confirmed that the issue occurs correctly work in the React Native WebView environment, but it causes errors in non-React Native WebView environment.
> 
> Therefore, this issue has been resolved in version 1.5.3.
> 
> Here is the CodeSandbox for version 1.5.3 on the same codebase: https://codesandbox.io/p/devbox/bridge-error-forked-sfkq6w
> 
> Let me know if you need any more changes!

Yes that fixes the issue thanks! Great work!

I don't know if this is related or not, but now I'm getting an error when running via react-native and when using 

`const { isNativeMethodAvailable } = useBridgeStatus();`

![IMG_8469](https://github.com/gronxb/webview-bridge/assets/7465835/8a795295-d344-4e15-93d5-02bf8f3133f7)

**Comment by steelzeh** [comment]
I'm also getting these errors 

![CleanShot 2024-07-09 at 20 44 20@2x](https://github.com/gronxb/webview-bridge/assets/7465835/4b5bf127-1f62-4f8c-a636-99b990238e0f)

**Comment by gronxb** [comment]
This issue only occurs in the SSR environment 🫠

I think I need to create a separate field for initialState to hydrate the non-react-native state for the SSR environment.

For example, it should look something like this:
```tsx
createLinkBridgeProvider<AppBridge>({
    throwOnError: true,
     // this field
     initialState: {
          requestLocation: () => {},
          text: "",
     },
     onReady: () => {
      console.log("bridge is ready");
    },
  });
```

Thank you. I will prepare it as soon as I have time.

**Comment by steelzeh** [comment]
Thank you for looking into this!

Wouldn't this also open up the possibility to test without having to run the react-native part, as you could mock the response?

**Comment by gronxb** [comment]
That’s right. It will be included in `linkBridge` and will be extended to by `createLinkBridgeProvider`. Once this feature is implemented, mocking will be possible when not in a React Native environment.

Thank you for the inspiration

**Comment by gronxb** [comment]
@steelzeh 

The issue has been resolved in version 1.6.0.

Please check again using the following link:
[CodeSandbox Project](https://codesandbox.io/p/devbox/bridge-error-forked-sfkq6w?file=%2Fapp%2Fproviders.tsx%3A12%2C1-35%2C1)

By using the `initialBridge` field, you can mock the behavior and ensure that values are displayed correctly even when not in a React Native environment.

```tsx

export const {
  BridgeProvider,
  useBridgeStore,
  useBridgeStatus,
  useBridgeLoose,
} = createLinkBridgeProvider<AppBridge>({
  throwOnError: true,
  timeout: 30000,
  // this field
  initialBridge: {
    requestLocation: async () => {
      alert("requestLocation is mocking");
      return "I'm from native";
    },
  },
  onReady: (bridge) => {
    if (!bridge.isWebViewBridgeAvailable) {
      console.log("Bridge not available");
      return;
    }
  },
});
```

**Comment by steelzeh** [comment]
@gronxb  Here is the updated codesandbox with the error 😄 
[sandbox](https://codesandbox.io/p/devbox/bridge-error-forked-sgd29j)

**Comment by gronxb** [comment]
I have reviewed the sandbox you provided. You need to add `'use client'` to the `page.tsx` file.

After downloading the provided sandbox and adding 'use client', it worked correctly. I also recommend clearing your `.next` and `node_modules` folders to ensure everything is set up properly.

Additionally, the reason `isWebViewBridgeAvailable` is true is due to mocking. For more details, please refer to the release notes: https://github.com/gronxb/webview-bridge/releases/tag/v1.6.0.

If you don’t want `isWebViewBridgeAvailable` to be false, I have confirmed that it works even without the `initialBridge`. Additionally, I have verified that it work in an SSR environment even without the `initialBridge`.

To check for a React Native environment, the following code snippet might be helpful:
```
const isReactNative = Boolean(window.ReactNativeWebView);
```

**Comment by gronxb** [comment]
In CodeSandbox, there seems to be an issue where changes to the code are not updating immediately with HMR. Despite deleting all the code in page.tsx, the same error persists as if the code wasn’t deleted. 😭 However, when I downloaded the code and checked it locally, it worked.

```diff
diff --git a/app/providers.tsx b/app/providers.tsx
index c68863b..205daef 100644
--- a/app/providers.tsx
+++ b/app/providers.tsx
@@ -1,3 +1,4 @@
+"use client";
 import { createLinkBridgeProvider } from "@webview-bridge/react";
 import type { Bridge, BridgeStore } from "@webview-bridge/web";
 import { LocationProvider } from "./LocationProvider";
```

**Comment by steelzeh** [comment]
Hmm, I don't know if this only happens when used in a layout maybe, this happens both locally and on codesandbox

I have updated it here [sandbox](https://codesandbox.io/p/devbox/bridge-error-forked-sgd29j) also when using "use client"

Maybe I'm misunderstanding something 😄

**Comment by gronxb** [comment]
I have completed the test in the provided sandbox. Please try with version 1.6.1.

**Comment by steelzeh** [comment]
It works!

Thank you for doing this amazing work, I really appreciate it!
