### ISSUE TITLE
Static html or react support

### ISSUE THREAD

**Issue by qalqi** [gronxb/webview-bridge#61]
All the shared examples require us to host the website. 
Is it possible to use webview-bridge using static html or react thats packed along with react native app?

**Comment by gronxb** [comment]
what do you mean by using it in static HTML? Do you mean a case like this?

```tsx
<WebView 
    source={{ html: `
        <script>
            const bridge = linkBridge();
            bridge.openInAppBrowser("https://www.google.com/");
         </script>
         <h1>This is a static HTML source!</h1>
`}}
/>
```

And what do you mean by using it in React? The webview-bridge is currently usable in React. Are you referring to using React via CDN as described here https://react.dev/blog/2024/04/25/react-19-upgrade-guide#umd-builds-removed

**Comment by qalqi** [comment]
yes! thanks for shared example for react! But, Can this react code be traspiled locally and inserted as html automatically while also generating the required types as suggested in this tutorial?  https://javascript.plainenglish.io/how-to-integrate-react-native-web-existing-react-native-apps-8e4964ad2f0b
In my case, I have p5js, p5js audio, react and need webview bridge to react native.

**Comment by gronxb** [comment]
This example was recorded in a non-deployed web environment.
https://github.com/user-attachments/assets/2388b77b-5440-46ae-9743-60f18520b0ee

Please check the link below:
[Example](https://github.com/gronxb/webview-bridge/tree/main/example/static-html/react-native)
[Web Code (web/index.ts)](https://github.com/gronxb/webview-bridge/blob/main/example/static-html/react-native/web/src/index.ts)
[React Native Code (App.tsx)](https://github.com/gronxb/webview-bridge/blob/main/example/static-html/react-native/App.tsx)
[Webpack Config](https://github.com/gronxb/webview-bridge/blob/main/example/static-html/react-native/webpack.config.js)



In this React Native project, I created a simple web page and bundled it using webpack.

Bundling was done with HtmlInlineScriptPlugin, which inserts all code into the HTML.

In this project, running

```sh
> pnpm webpack
```

will generate `dist/index.html` from the code in `web/src/index.ts`.

The WebView can be used as follows:
```tsx
<WebView
  // 1. pnpm webpack (output: dist/index.html)
  source={require("./dist/index.html")}
  style={{ height: "100%", flex: 1, width: "100%" }}
/>
```

Although I did not use react-native-web and react as you provided, the structure I used is sufficiently expandable with React.

Let me know if you need assistance!

**Comment by gronxb** [comment]
I'll mark this issue as resolved and close it.

**Comment by gronxb** [comment]
@qalqi 

I have confirmed that using require to import from the webview source is not functioning smoothly in a production environment. Related issue: https://github.com/react-native-webview/react-native-webview/issues/746#issuecomment-516350019

To ensure imports web app in production, I have created a new guide. Please review it:

Guide: https://gronxb.github.io/webview-bridge/static-html.html
Example code: https://github.com/gronxb/webview-bridge/tree/main/example/static-html

If you have any questions or requests, please feel free to open an issue. Thank you!
