### ISSUE TITLE
Error when accessing static HTML file in WebView: "TypeError: Cannot convert null value to object"

### ISSUE THREAD

**Issue by aumgiri9393** [gronxb/webview-bridge#66]
Hello,

I encountered an issue while using the webview-bridge library in my React Native project, which also contains a web project. I generate a static HTML file using webpack in my web project, and the file gets created successfully in the dist/ folder. However, when I try to access this file using the WebView component in my React Native app, I receive the following error:

```
Warning: TypeError: Cannot convert null value to object

This error is located at:
    in Unknown
    in Unknown (created by App)
    in RCTSafeAreaView (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in webViewPOC(RootComponent), js engine: hermes
``` 

I have created an example app demonstrating the issue, which you can find here: https://github.com/aumgiri9393/webViewPOC

Looking forward to your insights on resolving this issue. Thanks for your help!

**Comment by aumgiri9393** [comment]
Hi @gronxb,
Thank you so much for your prompt response and for resolving the issue! I really appreciate the support.  It’s working perfectly now.
Thanks again for the help

**Comment by gronxb** [comment]
@aumgiri9393 

I have confirmed that using require to import from the webview source is not functioning smoothly in a production environment. Related issue: https://github.com/react-native-webview/react-native-webview/issues/746#issuecomment-516350019

To ensure imports web app in production, I have created a new guide. Please review it:

Guide: https://gronxb.github.io/webview-bridge/static-html.html
Example code: https://github.com/gronxb/webview-bridge/tree/main/example/static-html

If you have any questions or requests, please feel free to open an issue. Thank you!
