### ISSUE TITLE
API design recommendation: web and native API definitions should be in the same file.

### ISSUE THREAD

**Issue by codecomeon** [gronxb/webview-bridge#8]
I suggest that for most scenarios, where RN (React Native) and Web projects are not organized as a monorepo, exporting TypeScript (TS) files can be a suitable approach to keep the two projects in sync. However, the interaction between the two sides is usually intertwined. By merging them together, we can simplify the process and reduce the cognitive burden of distinguishing which side's interface is being used.

Furthermore, as we move forward, adding functionalities like subscription channels and error handling should also be defined in the same file. This approach minimizes maintenance costs and enhances scalability, as code bundling is the responsibility of the bundler, and our focus should be on maintainability.

Therefore, my suggestion is to adopt a methodology where both APIs are consistently declared in the same file, without the need for exporting TS files by some scripts.

**Comment by gronxb** [comment]
Thank you for your opinion. Can you give me your opinion in English?

**Comment by codecomeon** [comment]
I suggest that for most scenarios, where RN (React Native) and Web projects are not organized as a monorepo, exporting TypeScript (TS) files can be a suitable approach to keep the two projects in sync. However, the interaction between the two sides is usually intertwined. By merging them together, we can simplify the process and reduce the cognitive burden of distinguishing which side's interface is being used.

Furthermore, as we move forward, adding functionalities like subscription channels and error handling should also be defined in the same file. This approach minimizes maintenance costs and enhances scalability, as code bundling is the responsibility of the bundler, and our focus should be on maintainability.

Therefore, my suggestion is to adopt a methodology where both APIs are consistently declared in the same file, without the need for exporting TS files by some scripts.

**Comment by codecomeon** [comment]
> I suggest that for most scenarios, where RN (React Native) and Web projects are not organized as a monorepo, exporting TypeScript (TS) files can be a suitable approach to keep the two projects in sync. However, the interaction between the two sides is usually intertwined. By merging them together, we can simplify the process and reduce the cognitive burden of distinguishing which side's interface is being used.
> 
> Furthermore, as we move forward, adding functionalities like subscription channels and error handling should also be defined in the same file. This approach minimizes maintenance costs and enhances scalability, as code bundling is the responsibility of the bundler, and our focus should be on maintainability.
> 
> Therefore, my suggestion is to adopt a methodology where both APIs are consistently declared in the same file, without the need for exporting TS files by some scripts.

There's a example file named WebviewProtocol.d.ts same at both RN and Web:
```
import {AppMethod, WebMethod} from '@webview-bridge/protocol';

export interface appMethod extends AppMethod {
  getMessage(): Promise<"I'm from native">;
};

export interface webMethod extends WebMethod {
  alert(message: string): Promise<void>;
  sum(a: number, b: number): Promise<number>;
};

... further functions
```

**Comment by gronxb** [comment]
Thank you for your suggestion.

Firstly, building interfaces in the same file can be challenging because specific libraries might be used exclusively in react-native, or there might be code accessing the DOM or the window object in web projects. 

For example,  It's an extreme but illustrated a scenario where each domain's respective library is returned, such as using `InAppBrowser` for react-native and accessing the `window` object in web projects. This approach indeed raises concerns about build failures or complexities during bundling since `InAppBrowser` is not buildable in a web project and the `window` object is absent in react-native projects.


```ts
import {AppMethod, WebMethod} from '@webview-bridge/protocol';
import InAppBrowser from "react-native-inappbrowser-reborn";
import ReactDOM from "react-dom";

export interface appMethod extends AppMethod {
  getInAppBrowser(): Promise<InAppBrowser>; // only native
};

export interface webMethod extends WebMethod {
  getWindowObject(message: string): Promise<typeof window>; // only web
};
```

Secondly, while it's advisable to use native methods in web environments, it's not recommended to interconnect web methods with native methods bidirectionally. This is because sharing types in both directions can be quite challenging. In many scenarios, calling native methods from the web and using their return values can be a sufficient approach. However, not all situations can be addressed this way, hence considering the connection of `webMethod` as a last resort.

Thinking of react-native as a server and web as a client, `webMethod` would be somewhat akin to a `server send event`. In typical scenarios, clients can resolve most issues even without server send events, which has informed your design approach.

**Comment by codecomeon** [comment]
> Thank you for your suggestion.
> 
> Firstly, building interfaces in the same file can be challenging because specific libraries might be used exclusively in react-native, or there might be code accessing the DOM or the window object in web projects.
> 
> For example, It's an extreme but illustrated a scenario where each domain's respective library is returned, such as using `InAppBrowser` for react-native and accessing the `window` object in web projects. This approach indeed raises concerns about build failures or complexities during bundling since `InAppBrowser` is not buildable in a web project and the `window` object is absent in react-native projects.
> 
> ```ts
> import {AppMethod, WebMethod} from '@webview-bridge/protocol';
> import InAppBrowser from "react-native-inappbrowser-reborn";
> import ReactDOM from "react-dom";
> 
> export interface appMethod extends AppMethod {
>   getInAppBrowser(): Promise<InAppBrowser>; // only native
> };
> 
> export interface webMethod extends WebMethod {
>   getWindowObject(message: string): Promise<typeof window>; // only web
> };
> ```
> 
> Secondly, while it's advisable to use native methods in web environments, it's not recommended to interconnect web methods with native methods bidirectionally. This is because sharing types in both directions can be quite challenging. In many scenarios, calling native methods from the web and using their return values can be a sufficient approach. However, not all situations can be addressed this way, hence considering the connection of `webMethod` as a last resort.
> 
> Thinking of react-native as a server and web as a client, `webMethod` would be somewhat akin to a `server send event`. In typical scenarios, clients can resolve most issues even without server send events, which has informed your design approach.
> 
> In most cases, connecting only native methods from the web should be sufficient and not pose significant maintenance issues. However, if you believe there are scenarios where additional connections are necessary, please feel free to share your thoughts or specific use cases. Thank you for your consideration in this matter.

You can see, when web invoke app method, web will not expect get a Native result from function returns, and same, native invoke web method will pass valid param rather than a Native Object.

I mean that, protocol must only define valid parameters and valid return value for all methods, the "valid" type should be Pure Value, String, Number, Pure Object, Array, and so on.

**Comment by codecomeon** [comment]
I think about a new scene(another idea)，Shared State for Native and web，State Change from one side will automatic shared to the other side，it maybe useful~

**Comment by gronxb** [comment]
I understood it to mean that even the files that run in the runtime should be written in one file. Sorry about that.

The idea of managing everything in a single file that only defines types for both bridges seems good.

What I was aiming for was to utilize type inference as much as possible. However, in cases that are not monorepos, there might be situations where direct definitions are needed, so it seems useful. 😁

**Comment by gronxb** [comment]
> I think about a new scene(another idea)，Shared State for Native and web，State Change from one side will automatic shared to the other side，it maybe useful~

Even if all types are defined in one file, isn't it true that the experience of automatically reflecting these changes in both projects is not possible unless it's a monorepo?

**Comment by gronxb** [comment]
It took a while, but with the introduction of `postMessage` replacing `registerWebMethod` and `linkWebMethod`, you can now declare types exclusively within React Native code.

Alternatively, you can create a shared file to maintain types in a single location.

Therefore, closing this issue. Thank you!

 Check it out here: [Using a post message](https://gronxb.github.io/webview-bridge/using-a-post-message.html)
