### ISSUE TITLE
Issue with Multiple Bridges in WebView Rendering State Changes in Real Time

### ISSUE THREAD

**Issue by aumgiri9393** [gronxb/webview-bridge#85]
Hi @gronxb ,
First of all, thank you for the fantastic work on this library. I’ve been integrating it into my React Native app, and it’s been great so far.However, I’ve encountered an issue when using multiple WebView bridges across different screens.
Problem Description:
I am using different bridges for different screens, each with its own state and methods in the bridge. The issue I’m facing is:
	1.	When the state is updated from the React Native side, only the first WebView on the first screen renders the changes in real time.
	2.	Other screens with their respective bridges update their states in the background, but the updates are not rendered in real time.
	3.	If I navigate back to a screen (with a different bridge) and open it again, the updated state is correctly accessed and rendered.

This suggests the state is being updated correctly in the background but is not triggering a re-render for WebViews other than the first one.

I’ve created a minimalistic React Native app that reproduces this issue.
Which you can find here: https://github.com/aumgiri9393/webViewPOC/tree/render-issue

I have attached a screen recording demonstrating the issue. You can see that only the first WebView reflects the state changes in real time. Other WebViews update the state in the background but do not re-render until revisited.

https://github.com/user-attachments/assets/fa8d6683-4dbc-49eb-8044-1e4092a3a0c8

I would appreciate any guidance or suggestions on how to resolve this.

**Comment by gronxb** [comment]
@aumgiri9393 

Hello,

It seems that the issue arises because multiple linkBridge instances share the `window.nativeEmitter` from the first created linkBridge for communication.

https://github.com/gronxb/webview-bridge/blob/ca3051ac92718946d2c236fb42d9457f4dcf09b7/packages/web/src/linkBridge.ts#L95-L98

To resolve this, I believe it’s necessary to create a unique `window.nativeEmitter[uniqueId]` for each instance.

Although I’ve identified the problem, it might take some time to implement a solution as I’m currently busy with work due to a recent job change.

I’ll do my best to address this issue as soon as my resources allow. Thank you for your understanding.

**Comment by gronxb** [comment]
Publish a draft of that PR: #86 

If the issue is urgent for you and can't wait, you can also send a pull request.

**Comment by aumgiri9393** [comment]
Hi @gronxb,
Thank you for your response and for providing the fix in the other branch. I’ve cloned it and tested it in my project.  I’ve observed the following:
	1.	Real-Time Updates Across Bridges:
Now, none of the bridges are updating in real time when the state changes from the React Native side. The issue persists across all screens.
	2.	bridgeId Assignment:
I’m unable to assign a bridgeId when using createWebView, which might be contributing to the issue in my case.

I completely understand that you’re busy and don’t want to pressure you to roll out the fix. When you have time, I’d appreciate any additional guidance or clarification on the bridgeId usage or other ways to ensure state updates reflect in real time across all WebViews.
Thank you again for your work and support!

**Comment by gronxb** [comment]
The issue has been resolved. Please update all versions to 1.7.3 and try again.

https://github.com/gronxb/webview-bridge/pull/86

**Comment by gronxb** [comment]
https://github.com/user-attachments/assets/8de9f19a-e865-465a-84a8-8db5c0190567

```sh
> yarn dev:web --force
> yarn start --reset-cache
```

```diff
--- a/package.json
+++ b/package.json
@@ -14,9 +14,9 @@
   "dependencies": {
     "@react-navigation/native": "^7.0.13",
     "@react-navigation/native-stack": "^7.1.14",
-    "@webview-bridge/react": "^1.6.2",
-    "@webview-bridge/react-native": "^1.6.2",
-    "@webview-bridge/web": "^1.6.2",
+    "@webview-bridge/react": "^1.7.3",
+    "@webview-bridge/react-native": "^1.7.3"
```

```diff
--- a/Screen1.tsx
+++ b/Screen1.tsx
@@ -1,4 +1,3 @@
-import './App.css';
 import { useBridge } from '@webview-bridge/react';
 import React from 'react';
 import { bridge, BridgeWebView } from '@webview-bridge/react-native';
```

In your code, I replaced it with the following and found it works fine.

**Comment by aumgiri9393** [comment]
Hi @gronxb ,

Thank you so much for addressing this issue and providing a fix! I really appreciate your prompt response and effort in maintaining this library.

I’ve tested the solution, and everything is working perfectly now. I’m closing the issue. Thanks again for your help! 😊
